### ISSUE TITLE
Strange default IP grup

### ISSUE THREAD

**Issue by wkoprek** [paulscherrerinstitute/PsiIpPackage#42]
When no IP group is defined in the package.tcl (no set_taxonomy), then strange characters are added as default group:

```
       <xilinx:taxonomies>
        <xilinx:taxonomy>{&quot;/UserIP&quot;}</xilinx:taxonomy>
      </xilinx:taxonomies>

```

**Comment by patrick-studer** [comment]
@jonasppsi 

I guess this issue is related to a wrong default setting of IpTaxonomy.
![image](https://user-images.githubusercontent.com/6918964/162455656-6f11306b-70fb-4e3a-a451-be1ced30c8d8.png)

There should not be a second set of curly brackets {}!
In the current implementation, the list has only ONE element that is called {"/UserIP"} what is clearly wrong.

@wkoprek 
Is the error fixed by removing the inner set of the {} at [here](https://github.com/paulscherrerinstitute/PsiIpPackage/blob/18db365d3aa90ef74414169478652721f44b3519/IpPackage2017_2_1.tcl#L81)

A correct list would be {"/Group1" "/Group2/Subgroup1"}

**Comment by wkoprek** [comment]
Exactly. By removing the inner {} the IP group is correct.

**Comment by jonasppsi** [comment]
Pushed fix. 33411af
